#!/usr/bin/env bash
#
# Copyright 2026 Franco
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -euo pipefail

readonly ROOT="$(dirname "$0")/.."
readonly FRAMES="$ROOT/goku/frames"
readonly OUTPUT="$ROOT/keyboards/crkbd/keymaps/vial/oled_goku_frames.h"
readonly -a ANIMATIONS=(
    base-idle
    base-to-ssj
    ssj-idle
    ssj-to-ssj2
    ssj2-idle
    ssj2-to-ssj3
    ssj3-idle
    ssj3-to-ssj4
    ssj4-idle
    ssj4-to-base
)

for animation in "${ANIMATIONS[@]}"; do
    for frame in 1 2 3; do
        path="$FRAMES/$animation-$frame.png"
        if [[ ! -f "$path" ]]; then
            printf 'Missing OLED frame: %s\n' "$path" >&2
            exit 1
        fi
        read -r width height colors < <(identify -format '%w %h %k\n' "$path")
        if ((width != 32 || height != 96 || colors != 2)); then
            printf 'Expected a two-color 32x96 OLED frame: %s\n' "$path" >&2
            exit 1
        fi
    done
done

{
    printf '%s\n' '/*'
    printf '%s\n' ' Copyright 2026 Franco'
    printf '%s\n' ''
    printf '%s\n' ' This program is free software: you can redistribute it and/or modify'
    printf '%s\n' ' it under the terms of the GNU General Public License as published by'
    printf '%s\n' ' the Free Software Foundation, either version 2 of the License, or'
    printf '%s\n' ' (at your option) any later version.'
    printf '%s\n' ''
    printf '%s\n' ' This program is distributed in the hope that it will be useful,'
    printf '%s\n' ' but WITHOUT ANY WARRANTY; without even the implied warranty of'
    printf '%s\n' ' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the'
    printf '%s\n' ' GNU General Public License for more details.'
    printf '%s\n' ''
    printf '%s\n' ' You should have received a copy of the GNU General Public License'
    printf '%s\n' ' along with this program. If not, see <http://www.gnu.org/licenses/>.'
    printf '%s\n' ''
    printf '%s\n' ' Generated by goku/generate_oled_frames.sh; do not edit manually.'
    printf '%s\n' '*/'
    printf '\n'
    printf '%s\n' '#pragma once'
    printf '\n'
    printf '%s\n' '#define OLED_GOKU_FRAME_WIDTH             32'
    printf '%s\n' '#define OLED_GOKU_FRAME_HEIGHT            96'
    printf '%s\n' '#define OLED_GOKU_FRAME_BYTES             (OLED_GOKU_FRAME_WIDTH * OLED_GOKU_FRAME_HEIGHT / 8)'
    printf '%s\n' '#define OLED_GOKU_FRAMES_PER_ANIMATION    3'
    printf '%s\n' '#define OLED_GOKU_ANIMATION_COUNT         10'
    printf '%s\n' '#define OLED_GOKU_FRAME_COUNT             (OLED_GOKU_ANIMATION_COUNT * OLED_GOKU_FRAMES_PER_ANIMATION)'
    printf '%s\n' '#define OLED_GOKU_Y                       32'
    printf '%s\n' '#define OLED_GOKU_IDLE_DURATION           5000'
    printf '%s\n' '#define OLED_GOKU_IDLE_FRAME_DURATION     250'
    printf '%s\n' '#define OLED_GOKU_TRANSFORMATION_FRAME_DURATION 200'
    printf '%s\n' '#define OLED_GOKU_TRANSFORMATION_DURATION (OLED_GOKU_TRANSFORMATION_FRAME_DURATION * OLED_GOKU_FRAMES_PER_ANIMATION)'
    printf '\n'
    printf '%s\n' 'static const uint8_t PROGMEM oled_goku_frames[OLED_GOKU_FRAME_COUNT][OLED_GOKU_FRAME_BYTES] = {'

    for animation in "${ANIMATIONS[@]}"; do
        for frame in 1 2 3; do
            printf '    /* %s frame %s */\n' "$animation" "$frame"
            printf '%s\n' '    {'
            magick "$FRAMES/$animation-$frame.png" -background white -alpha remove -alpha off -colorspace sRGB txt:- | perl -ne '
                if (/([0-9]+),([0-9]+): \(([0-9]+),/) {
                    $pixels[$2][$1] = $3 < 128;
                }
                END {
                    $count = 0;
                    for ($page = 0; $page < 12; $page++) {
                        for ($x = 0; $x < 32; $x++) {
                            $byte = 0;
                            for ($bit = 0; $bit < 8; $bit++) {
                                # OLED pixels are lit for the white background and off for the black character ink.
                                $byte |= 1 << $bit unless $pixels[$page * 8 + $bit][$x];
                            }
                            print "        " if $count % 16 == 0;
                            printf "0x%02X,", $byte;
                            $count++;
                            print "\n" if $count % 16 == 0;
                        }
                    }
                }
            '
            printf '%s\n' '    },'
        done
    done

    printf '%s\n' '};'
} > "$OUTPUT"
